'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { MessagesSquare, Plus } from 'lucide-react';
import { SiteHeader } from './site-header';
import type { Role } from '@/lib/roles';
import { CustomerNav } from './customer-nav';
import { inquiryLabels, type Inquiry } from '@/lib/discovery';
import { catalogRequest } from '@/lib/catalog-client';

export function CustomerInquiries({role}:{role:Role}){
  const [data,setData]=useState<{items:Inquiry[];total:number}|null>(null),[error,setError]=useState(''),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(true),[checking,setChecking]=useState<string|null>(null),[notice,setNotice]=useState('');
  useEffect(()=>{const controller=new AbortController();catalogRequest<{items:Inquiry[];total:number}>(`/api/customer/inquiries?page=${page}&pageSize=12`,{signal:controller.signal}).then(result=>{setData(result);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error ? e.message:'Chưa thể tải yêu cầu.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[page,attempt]);
  async function confirm(id:string){setChecking(id);setNotice('');try{const result=await catalogRequest<{status:keyof typeof inquiryLabels}>(`/api/customer/inquiries/${id}/confirm`,{method:'POST'});setNotice(result.status==='PendingVerification' ? 'Số điện thoại trong yêu cầu chưa được xác minh. Hãy xác minh đúng số trong hồ sơ cá nhân.':inquiryLabels[result.status]);setAttempt(attempt+1);}catch(e){setNotice(e instanceof Error ? e.message:'Chưa thể kiểm tra xác minh.');}finally{setChecking(null);}}
  return <><SiteHeader role={role}/><main className="discovery-main container"><CustomerNav active="inquiries"/><div className="customer-section-heading discovery-heading"><div><span className="eyebrow">THEO DÕI NHU CẦU CỦA BẠN</span><h1>Yêu cầu tư vấn</h1><p>Xem thông tin đã gửi và trạng thái tiếp nhận.</p></div><Link href="/customer/inquiries/new" className="button primary"><Plus size={17}/> Yêu cầu mới</Link></div>{notice && <p className="inquiry-notice" role="status">{notice}</p>}{busy ? <p className="customer-empty" role="status">Đang tải yêu cầu…</p> : error ? <div className="customer-empty" role="alert"><p>{error}</p><button className="button secondary" onClick={()=>{setBusy(true);setAttempt(attempt+1);}}>Thử lại</button></div> : data?.items.length ? <><div className="customer-inquiry-list">{data.items.map(inquiry=><article key={inquiry.id} className="customer-inquiry-card"><div className="customer-section-heading"><h2>{inquiry.property_name || 'Tư vấn theo nhu cầu'}</h2><span className={`inquiry-status ${inquiry.status}`}>{inquiryLabels[inquiry.status]}</span></div><p className="inquiry-date">Gửi lúc {new Date(inquiry.created_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} · Mã {inquiry.id.slice(0,8)}</p>{inquiry.message && <p className="property-description">{inquiry.message}</p>}<dl className="property-detail-facts"><div><dt>Kênh liên hệ</dt><dd>{inquiry.channel==='Email' ? 'Email':'Điện thoại'}</dd></div><div><dt>Số điện thoại</dt><dd>{inquiry.phone}</dd></div><div><dt>Email</dt><dd>{inquiry.email}</dd></div>{inquiry.preferred_time && <div><dt>Thời gian phù hợp</dt><dd>{inquiry.preferred_time}</dd></div>}</dl><p className="inquiry-permissions">Gọi tư vấn: {inquiry.consent.call ? 'Đồng ý':'Không đồng ý'} · AI giọng nói: {inquiry.consent.ai ? 'Đồng ý':'Không đồng ý'} · Bản chép lời: {inquiry.consent.transcript ? 'Đồng ý':'Không đồng ý'} · Ghi âm: {inquiry.consent.recording ? 'Đồng ý':'Không đồng ý'}</p>{inquiry.status==='PendingVerification' && <div className="inquiry-followup"><p>Lưu và xác minh đúng số điện thoại trong hồ sơ để hoàn tất thông tin liên hệ.</p><Link href="/account" className="text-link">Mở hồ sơ để xác minh</Link><button className="button secondary" disabled={checking===inquiry.id} onClick={()=>confirm(inquiry.id)}>Kiểm tra xác minh</button></div>}</article>)}</div><div className="discovery-pagination"><button className="button secondary" disabled={page===1} onClick={()=>{setBusy(true);setPage(page-1);}}>Trang trước</button><span>Trang {page} / {Math.ceil(data.total/12)}</span><button className="button secondary" disabled={page*12>=data.total} onClick={()=>{setBusy(true);setPage(page+1);}}>Trang sau</button></div></> : <div className="customer-empty"><MessagesSquare size={32}/><h2>Chưa có yêu cầu tư vấn</h2><p>Chọn một bất động sản hoặc chia sẻ nhu cầu của bạn để bắt đầu.</p><Link href="/properties" className="button primary">Khám phá bất động sản</Link></div>}</main></>;
}
