import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Building2, Check, ClipboardList, FolderKanban, Layers3, ShieldCheck, UsersRound } from 'lucide-react';
import { SiteHeader } from './site-header';
import { Brand } from './brand';
import { HomeActions } from './home-actions';

export function WorkflowPreview() {
  return <div className="workflow-preview" aria-label="Quy trình tổ chức thông tin bất động sản"><div className="preview-top"><span className="preview-logo"><Layers3 size={18}/> NEXCALL WORKSPACE</span><span className="demo-badge">Kết nối thông tin</span></div><div className="preview-title"><span className="eyebrow">DỰ ÁN → SẢN PHẨM → ĐỘI NGŨ</span><h3>Mọi thông tin, một không gian.</h3></div><div className="workflow-node"><span className="workflow-icon"><FolderKanban size={22}/></span><div><strong>Tổ chức danh mục</strong><small>Dự án, phân khu và tiện ích</small></div><span className="workflow-number">01</span></div><div className="workflow-connector"/><div className="workflow-node active"><span className="workflow-icon"><Building2 size={22}/></span><div><strong>Quản lý sản phẩm</strong><small>Nội dung, tài liệu và tình trạng mở bán</small></div><span className="workflow-number">02</span></div><div className="workflow-connector"/><div className="workflow-node"><span className="workflow-icon"><UsersRound size={22}/></span><div><strong>Kết nối đội ngũ</strong><small>Không gian phù hợp cho từng vai trò</small></div><span className="workflow-number">03</span></div><div className="preview-bottom"><ShieldCheck size={16}/> Thông tin rõ ràng · Truy cập có kiểm soát</div></div>;
}

const features = [
  { icon: Building2, name: 'Danh mục bất động sản', text: 'Sắp xếp dự án, phân khu và sản phẩm để đội ngũ có cùng một nguồn thông tin.' },
  { icon: FolderKanban, name: 'Tài liệu tập trung', text: 'Quản lý hình ảnh và tài liệu sản phẩm, chủ động chọn phạm vi hiển thị công khai hoặc nội bộ.' },
  { icon: ClipboardList, name: 'Cập nhật minh bạch', text: 'Theo dõi trạng thái công bố, tình trạng mở bán và lịch sử thay đổi của từng sản phẩm.' },
  { icon: ShieldCheck, name: 'Không gian theo vai trò', text: 'Tài khoản khách hàng, nhân viên tư vấn và quản trị viên có phạm vi truy cập phù hợp.' },
];

export function SystemHome() {
  return <><SiteHeader role={null}/><main className="system-main"><section className="hero system-hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span/> PROPERTY & CUSTOMER WORKSPACE</span><h1>Thông tin rõ ràng.<br/>Kết nối khách hàng<br/><em>hiệu quả.</em></h1><p>NexCall kết nối thông tin bất động sản, khách hàng và đội ngũ tư vấn. Tổ chức danh mục, cập nhật sản phẩm và làm việc trong một không gian thống nhất.</p><HomeActions/><div className="hero-trust"><span><ShieldCheck size={17}/> Truy cập theo vai trò</span><span><UsersRound size={17}/> Đồng hành cùng đội ngũ tư vấn</span></div></div><WorkflowPreview/></div></section><section className="section container" id="chuc-nang"><div className="section-top"><div><span className="eyebrow">LÀM VIỆC RÕ RÀNG HƠN</span><h2>Thông tin đầy đủ. Phối hợp thuận tiện.</h2><p>Các công cụ giúp bạn quản lý danh mục và chủ động cập nhật thông tin mỗi ngày.</p></div><span className="demo-badge">Một không gian thống nhất</span></div><div className="system-feature-grid">{features.map(({icon:Icon,name,text})=><article key={name}><span className="benefit-icon"><Icon size={26}/></span><h3>{name}</h3><p>{text}</p></article>)}</div></section><section className="about-section" id="ve-nexcall"><div className="container system-about"><div><span className="eyebrow">VỀ NEXCALL</span><h2>Kết nối dữ liệu.<br/>Đồng hành cùng khách hàng.</h2><p>Mỗi sản phẩm có thông tin rõ ràng. Mỗi thành viên có không gian phù hợp. NexCall giúp đội ngũ quản lý danh mục nhất quán và tạo nền tảng cho những cuộc tư vấn hiệu quả.</p></div><div className="system-principles"><p><Check size={18}/> Tổ chức sản phẩm theo dự án và phân khu.</p><p><Check size={18}/> Cập nhật giá và tình trạng mở bán rõ ràng.</p><p><Check size={18}/> Quản lý hình ảnh và tài liệu tại một nơi.</p><p><Check size={18}/> Theo dõi thay đổi và kiểm soát quyền truy cập.</p></div></div></section><section className="container cta-section"><div><span className="eyebrow light">BẮT ĐẦU VỚI NEXCALL</span><h2>Một không gian.<br/>Nhiều kết nối giá trị.</h2><p>Tạo tài khoản khách hàng và quản lý thông tin cá nhân của bạn.</p></div><Link href="/sign-up" className="button white">Tạo tài khoản <ArrowUpRight size={19}/></Link><div className="cta-circle"/></section></main><footer className="site-footer container"><Brand/><span>© {new Date().getFullYear()} NexCall</span><Link href="/terms">Điều khoản & quyền riêng tư <ArrowRight size={14}/></Link></footer></>;
}
